# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 500a7987c9cb0c1a7ba116fa9608a5946d7440020c3dfe4562c40d945fbf40509424907d61637a22eec483b9449ac3125ecf9cc1bba64da3661b10dfb1730ca7

test:
  secret_key_base: 4945181a48dbcafc4b5d436925853b077fa8044ea8230b20e49a35a31f9d2c39f7326930f0408a1a7ff6aa4dcefe59b0df79b11b801534dee8c856811e05ed42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
